name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # tiap hari jam 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
      - uses: yoshi3d/github-profile-3d-contrib@master
        with:
          username: firdyridho
      - name: Commit hasil render
        run: |
          cd profile-3d-contrib
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generate 3D contribution graph" || exit 0
          git push
